{% set name = "pyperformance" %}
{% set version = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyperformance-{{ version }}.tar.gz
  sha256: 674fff4ade04766358fa13e8591dd8715303c9c4904db2615403a7b34da1485b

build:
  number: 0
  noarch: python
  entry_points:
    - pyperformance=pyperformance.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - packaging
    - pyperf
    - toml

test:
  imports:
    - pyperformance
  commands:
    - pip check
    - pyperformance --help
  requires:
    - pip

about:
  home: https://pyperformance.readthedocs.io
  summary: Python benchmark suite
  license: MIT
  license_file: COPYING
  dev_url: https://github.com/python/pyperformance
  doc_url: https://pyperformance.readthedocs.io

extra:
  recipe-maintainers:
    - mrakitin
